import { prisma } from "../../../../lib/prisma";
import { NextRequest, NextResponse } from "next/server";

interface PositionData {
  id?: string; // ID should be optional for creation, it's autogenerated
  name: string;
  wkn?: string;
  isin?: string;
  price?: number; // Use JavaScript's number type for Prisma's Float
  quantity?: number; // Use JavaScript's number type for Prisma's Float
  createdAt?: Date; // Use JavaScript's Date type for Prisma's DateTime
  updatedAt?: Date; // Use JavaScript's Date type for Prisma's DateTime
  ownerId?: string;
}

export async function GET(request: NextRequest) {
  try {
    const positions = await prisma.position.findMany({
      orderBy: {
        createdAt: "desc",
      },
    });
    return NextResponse.json(positions);
  } catch (error: any) {
    console.log(error);
  }
}

export async function POST(request: NextRequest) {
  try {
    const { body } = request;
    const position = await prisma.position.create({
      data: body,
    });
    return NextResponse.json(position);
  } catch (error: any) {
    console.log(error);
  }
}
